### ISSUE TITLE
下载时出现错误代码

### ISSUE THREAD

**Issue by zhuoruofuqu** [CyrusRenty/CNKI-download#29]
如下
Traceback (most recent call last):
  File "D:\Python-3.83\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "D:\Python-3.83\lib\site-packages\urllib3\connectionpool.py", line 930, in _prepare_proxy
    conn.connect()
  File "D:\Python-3.83\lib\site-packages\urllib3\connection.py", line 396, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "D:\Python-3.83\lib\site-packages\urllib3\connection.py", line 406, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "D:\Python-3.83\lib\ssl.py", line 416, in match_hostname
    raise CertificateError("hostname %r "
ssl.SSLCertVerificationError: ("hostname 'i.shufang.cnki.net' doesn't match either of '*.cnki.net', 'www.cnki.net', '*.global.cnki.net', '*.oversea.cnki.net', 'big5.book.oversea.cnki.net', 'caj.d.cnki.net', 'caj.oversea.d.cnki.net', 'en.cend.cnki.net', 'eng.tcm.cnki.net', 'gb.book.oversea.cnki.net', 'gb.cend.cnki.net', 'gb.cnbar.cnki.net', 'gb.obaor.cnki.net', 'gb.sczlmz.cnki.net', 'gb.sczlzj.cnki.net', 'gb.tcm.cnki.net', 'kb.tcm.cnki.net', 'oversea.d.cnki.net', 'pdf.d.cnki.net', 'pdf.oversea.d.cnki.net', 'tra.tcm.cnki.net', 'cnki.net'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python-3.83\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Python-3.83\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "D:\Python-3.83\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='i.shufang.cnki.net', port=443): Max retries exceeded with url: /KRS/KRSWriteHandler.ashx?curUrl=detail.aspx%3FdbCode%3DCJFQ%26fileName%3DTYGY20210331002&referUrl=https%3A%2F%2Fkns.cnki.net%2Fkns%2Fbrief%2Fbrief.aspx%3Fpagename%3DASP.brief_default_result_aspx%26isinEn%3D1%26dbPrefix%3DSCDB%26dbCatalog%3D%25e4%25b8%25ad%25e5%259b%25bd%25e5%25ad%25a6%25e6%259c%25af%25e6%259c%259f%25e5%2588%258a%25e7%25bd%2591%25e7%25bb%259c%25e5%2587%25ba%25e7%2589%2588%25e6%2580%25bb%25e5%25ba%2593%26ConfigFile%3DCJFQ.xml%26research%3Doff%26t%3D1544249384932%26keyValue%3D%25E8%25AF%25AD%25E9%259F%25B3%25E8%25AF%2586%25E5%2588%25AB%26S%3D1%26sorttype%3D%23J_ORDER%26&cnkiUserKey=d522e520-357b-a254-9bd3-9e95fdce484&action=file&userName=&td=1544605318654 (Caused by SSLError(SSLCertVerificationError("hostname 'i.shufang.cnki.net' doesn't match either of '*.cnki.net', 'www.cnki.net', '*.global.cnki.net', '*.oversea.cnki.net', 'big5.book.oversea.cnki.net', 'caj.d.cnki.net', 'caj.oversea.d.cnki.net', 'en.cend.cnki.net', 'eng.tcm.cnki.net', 'gb.book.oversea.cnki.net', 'gb.cend.cnki.net', 'gb.cnbar.cnki.net', 'gb.obaor.cnki.net', 'gb.sczlmz.cnki.net', 'gb.sczlzj.cnki.net', 'gb.tcm.cnki.net', 'kb.tcm.cnki.net', 'oversea.d.cnki.net', 'pdf.d.cnki.net', 'pdf.oversea.d.cnki.net', 'tra.tcm.cnki.net', 'cnki.net'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/ASUS/PycharmProjects/1111111/知网/CNKI-download-master/main.py", line 259, in <module>
    main()
  File "C:/Users/ASUS/PycharmProjects/1111111/知网/CNKI-download-master/main.py", line 253, in main
    search.search_reference(get_uesr_inpt())
  File "C:/Users/ASUS/PycharmProjects/1111111/知网/CNKI-download-master/main.py", line 98, in search_reference
    self.parse_page(
  File "C:/Users/ASUS/PycharmProjects/1111111/知网/CNKI-download-master/main.py", line 186, in parse_page
    page_detail.get_detail_page(self.session, self.get_result_url,
  File "C:\Users\ASUS\PycharmProjects\1111111\知网\CNKI-download-master\GetPageDetail.py", line 70, in get_detail_page
    self.session.get(
  File "D:\Python-3.83\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "D:\Python-3.83\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python-3.83\lib\site-packages\requests\sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "D:\Python-3.83\lib\site-packages\requests\sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "D:\Python-3.83\lib\site-packages\requests\sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "D:\Python-3.83\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python-3.83\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='i.shufang.cnki.net', port=443): Max retries exceeded with url: /KRS/KRSWriteHandler.ashx?curUrl=detail.aspx%3FdbCode%3DCJFQ%26fileName%3DTYGY20210331002&referUrl=https%3A%2F%2Fkns.cnki.net%2Fkns%2Fbrief%2Fbrief.aspx%3Fpagename%3DASP.brief_default_result_aspx%26isinEn%3D1%26dbPrefix%3DSCDB%26dbCatalog%3D%25e4%25b8%25ad%25e5%259b%25bd%25e5%25ad%25a6%25e6%259c%25af%25e6%259c%259f%25e5%2588%258a%25e7%25bd%2591%25e7%25bb%259c%25e5%2587%25ba%25e7%2589%2588%25e6%2580%25bb%25e5%25ba%2593%26ConfigFile%3DCJFQ.xml%26research%3Doff%26t%3D1544249384932%26keyValue%3D%25E8%25AF%25AD%25E9%259F%25B3%25E8%25AF%2586%25E5%2588%25AB%26S%3D1%26sorttype%3D%23J_ORDER%26&cnkiUserKey=d522e520-357b-a254-9bd3-9e95fdce484&action=file&userName=&td=1544605318654 (Caused by SSLError(SSLCertVerificationError("hostname 'i.shufang.cnki.net' doesn't match either of '*.cnki.net', 'www.cnki.net', '*.global.cnki.net', '*.oversea.cnki.net', 'big5.book.oversea.cnki.net', 'caj.d.cnki.net', 'caj.oversea.d.cnki.net', 'en.cend.cnki.net', 'eng.tcm.cnki.net', 'gb.book.oversea.cnki.net', 'gb.cend.cnki.net', 'gb.cnbar.cnki.net', 'gb.obaor.cnki.net', 'gb.sczlmz.cnki.net', 'gb.sczlzj.cnki.net', 'gb.tcm.cnki.net', 'kb.tcm.cnki.net', 'oversea.d.cnki.net', 'pdf.d.cnki.net', 'pdf.oversea.d.cnki.net', 'tra.tcm.cnki.net', 'cnki.net'")))
请求您的解答

**Comment by ChenLD3124** [comment]
请问您是怎样解决'NoneType' object has no attribute 'group'的啊

> 如下
> Traceback (most recent call last):
> File "D:\Python-3.83\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
> self._prepare_proxy(conn)
> File "D:\Python-3.83\lib\site-packages\urllib3\connectionpool.py", line 930, in _prepare_proxy
> conn.connect()
> File "D:\Python-3.83\lib\site-packages\urllib3\connection.py", line 396, in connect
> _match_hostname(cert, self.assert_hostname or server_hostname)
> File "D:\Python-3.83\lib\site-packages\urllib3\connection.py", line 406, in _match_hostname
> match_hostname(cert, asserted_hostname)
> File "D:\Python-3.83\lib\ssl.py", line 416, in match_hostname
> raise CertificateError("hostname %r "
> ssl.SSLCertVerificationError: ("hostname 'i.shufang.cnki.net' doesn't match either of '_.cnki.net', 'www.cnki.net', '_.global.cnki.net', '*.oversea.cnki.net', 'big5.book.oversea.cnki.net', 'caj.d.cnki.net', 'caj.oversea.d.cnki.net', 'en.cend.cnki.net', 'eng.tcm.cnki.net', 'gb.book.oversea.cnki.net', 'gb.cend.cnki.net', 'gb.cnbar.cnki.net', 'gb.obaor.cnki.net', 'gb.sczlmz.cnki.net', 'gb.sczlzj.cnki.net', 'gb.tcm.cnki.net', 'kb.tcm.cnki.net', 'oversea.d.cnki.net', 'pdf.d.cnki.net', 'pdf.oversea.d.cnki.net', 'tra.tcm.cnki.net', 'cnki.net'",)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "D:\Python-3.83\lib\site-packages\requests\adapters.py", line 439, in send
> resp = conn.urlopen(
> File "D:\Python-3.83\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
> retries = retries.increment(
> File "D:\Python-3.83\lib\site-packages\urllib3\util\retry.py", line 439, in increment
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='i.shufang.cnki.net', port=443): Max retries exceeded with url: /KRS/KRSWriteHandler.ashx?curUrl=detail.aspx%3FdbCode%3DCJFQ%26fileName%3DTYGY20210331002&referUrl=https%3A%2F%2Fkns.cnki.net%2Fkns%2Fbrief%2Fbrief.aspx%3Fpagename%3DASP.brief_default_result_aspx%26isinEn%3D1%26dbPrefix%3DSCDB%26dbCatalog%3D%25e4%25b8%25ad%25e5%259b%25bd%25e5%25ad%25a6%25e6%259c%25af%25e6%259c%259f%25e5%2588%258a%25e7%25bd%2591%25e7%25bb%259c%25e5%2587%25ba%25e7%2589%2588%25e6%2580%25bb%25e5%25ba%2593%26ConfigFile%3DCJFQ.xml%26research%3Doff%26t%3D1544249384932%26keyValue%3D%25E8%25AF%25AD%25E9%259F%25B3%25E8%25AF%2586%25E5%2588%25AB%26S%3D1%26sorttype%3D%23J_ORDER%26&cnkiUserKey=d522e520-357b-a254-9bd3-9e95fdce484&action=file&userName=&td=1544605318654 (Caused by SSLError(SSLCertVerificationError("hostname 'i.shufang.cnki.net' doesn't match either of '_.cnki.net', 'www.cnki.net', '_.global.cnki.net', '*.oversea.cnki.net', 'big5.book.oversea.cnki.net', 'caj.d.cnki.net', 'caj.oversea.d.cnki.net', 'en.cend.cnki.net', 'eng.tcm.cnki.net', 'gb.book.oversea.cnki.net', 'gb.cend.cnki.net', 'gb.cnbar.cnki.net', 'gb.obaor.cnki.net', 'gb.sczlmz.cnki.net', 'gb.sczlzj.cnki.net', 'gb.tcm.cnki.net', 'kb.tcm.cnki.net', 'oversea.d.cnki.net', 'pdf.d.cnki.net', 'pdf.oversea.d.cnki.net', 'tra.tcm.cnki.net', 'cnki.net'")))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:/Users/ASUS/PycharmProjects/1111111/知网/CNKI-download-master/main.py", line 259, in
> main()
> File "C:/Users/ASUS/PycharmProjects/1111111/知网/CNKI-download-master/main.py", line 253, in main
> search.search_reference(get_uesr_inpt())
> File "C:/Users/ASUS/PycharmProjects/1111111/知网/CNKI-download-master/main.py", line 98, in search_reference
> self.parse_page(
> File "C:/Users/ASUS/PycharmProjects/1111111/知网/CNKI-download-master/main.py", line 186, in parse_page
> page_detail.get_detail_page(self.session, self.get_result_url,
> File "C:\Users\ASUS\PycharmProjects\1111111\知网\CNKI-download-master\GetPageDetail.py", line 70, in get_detail_page
> self.session.get(
> File "D:\Python-3.83\lib\site-packages\requests\sessions.py", line 555, in get
> return self.request('GET', url, **kwargs)
> File "D:\Python-3.83\lib\site-packages\requests\sessions.py", line 542, in request
> resp = self.send(prep, **send_kwargs)
> File "D:\Python-3.83\lib\site-packages\requests\sessions.py", line 677, in send
> history = [resp for resp in gen]
> File "D:\Python-3.83\lib\site-packages\requests\sessions.py", line 677, in
> history = [resp for resp in gen]
> File "D:\Python-3.83\lib\site-packages\requests\sessions.py", line 237, in resolve_redirects
> resp = self.send(
> File "D:\Python-3.83\lib\site-packages\requests\sessions.py", line 655, in send
> r = adapter.send(request, **kwargs)
> File "D:\Python-3.83\lib\site-packages\requests\adapters.py", line 514, in send
> raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='i.shufang.cnki.net', port=443): Max retries exceeded with url: /KRS/KRSWriteHandler.ashx?curUrl=detail.aspx%3FdbCode%3DCJFQ%26fileName%3DTYGY20210331002&referUrl=https%3A%2F%2Fkns.cnki.net%2Fkns%2Fbrief%2Fbrief.aspx%3Fpagename%3DASP.brief_default_result_aspx%26isinEn%3D1%26dbPrefix%3DSCDB%26dbCatalog%3D%25e4%25b8%25ad%25e5%259b%25bd%25e5%25ad%25a6%25e6%259c%25af%25e6%259c%259f%25e5%2588%258a%25e7%25bd%2591%25e7%25bb%259c%25e5%2587%25ba%25e7%2589%2588%25e6%2580%25bb%25e5%25ba%2593%26ConfigFile%3DCJFQ.xml%26research%3Doff%26t%3D1544249384932%26keyValue%3D%25E8%25AF%25AD%25E9%259F%25B3%25E8%25AF%2586%25E5%2588%25AB%26S%3D1%26sorttype%3D%23J_ORDER%26&cnkiUserKey=d522e520-357b-a254-9bd3-9e95fdce484&action=file&userName=&td=1544605318654 (Caused by SSLError(SSLCertVerificationError("hostname 'i.shufang.cnki.net' doesn't match either of '_.cnki.net', 'www.cnki.net', '_.global.cnki.net', '*.oversea.cnki.net', 'big5.book.oversea.cnki.net', 'caj.d.cnki.net', 'caj.oversea.d.cnki.net', 'en.cend.cnki.net', 'eng.tcm.cnki.net', 'gb.book.oversea.cnki.net', 'gb.cend.cnki.net', 'gb.cnbar.cnki.net', 'gb.obaor.cnki.net', 'gb.sczlmz.cnki.net', 'gb.sczlzj.cnki.net', 'gb.tcm.cnki.net', 'kb.tcm.cnki.net', 'oversea.d.cnki.net', 'pdf.d.cnki.net', 'pdf.oversea.d.cnki.net', 'tra.tcm.cnki.net', 'cnki.net'")))
> 请求您的解答

请问您是怎样解决'NoneType' object has no attribute 'group'的啊
